# -*- coding: utf-8 -*-
"""Informed Search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H9sqZsWoKG8_au33vii1VNXMs5oVNrHP
"""

from queue import PriorityQueue
from copy import deepcopy

class PuzzleState:
    """Represents a state of the 8-puzzle"""

    def __init__(self, board, parent=None, move=None, depth=0):
        self.board = board
        self.parent = parent
        self.move = move
        self.depth = depth
        self.h_value = 0  # Heuristic value

    def __lt__(self, other):
        """Compare states based on heuristic value for priority queue"""
        return self.h_value < other.h_value

    def __eq__(self, other):
        """Check if two states are equal"""
        return self.board == other.board

    def __hash__(self):
        """Hash function for state comparison"""
        return hash(str(self.board))

    def get_blank_position(self):
        """Find the position of the blank tile (0)"""
        for i in range(3):
            for j in range(3):
                if self.board[i][j] == 0:
                    return i, j
        return None

    def is_goal(self, goal_state):
        """Check if current state is the goal state"""
        return self.board == goal_state.board

    def get_successors(self):
        """Generate all possible successor states"""
        successors = []
        blank_row, blank_col = self.get_blank_position()

        # Possible moves: Up, Down, Left, Right
        moves = [
            (-1, 0, "Up"),
            (1, 0, "Down"),
            (0, -1, "Left"),
            (0, 1, "Right")
        ]

        for dr, dc, move_name in moves:
            new_row = blank_row + dr
            new_col = blank_col + dc

            # Check if the move is valid
            if 0 <= new_row < 3 and 0 <= new_col < 3:
                # Create new board configuration
                new_board = deepcopy(self.board)
                # Swap blank with adjacent tile
                new_board[blank_row][blank_col] = new_board[new_row][new_col]
                new_board[new_row][new_col] = 0

                # Create new state
                successor = PuzzleState(new_board, self, move_name, self.depth + 1)
                successors.append(successor)

        return successors

    def display(self):
        """Display the puzzle board"""
        for row in self.board:
            print(" ".join(str(tile) if tile != 0 else "*" for tile in row))
        print()

def manhattan_distance(state, goal_state):
    """
    Calculate Manhattan distance heuristic
    Sum of distances of each tile from its goal position
    """
    distance = 0
    for i in range(3):
        for j in range(3):
            if state.board[i][j] != 0:  # Skip blank tile
                value = state.board[i][j]
                # Find goal position of this value
                for goal_i in range(3):
                    for goal_j in range(3):
                        if goal_state.board[goal_i][goal_j] == value:
                            distance += abs(i - goal_i) + abs(j - goal_j)
                            break
    return distance

def misplaced_tiles(state, goal_state):
    """
    Calculate misplaced tiles heuristic
    Count of tiles not in their goal position
    """
    count = 0
    for i in range(3):
        for j in range(3):
            if state.board[i][j] != 0 and state.board[i][j] != goal_state.board[i][j]:
                count += 1
    return count

def greedy_best_first_search(initial_state, goal_state, heuristic_func=manhattan_distance):
    """
    Greedy Best-First Search Algorithm

    Args:
        initial_state: Starting state of the puzzle
        goal_state: Goal state of the puzzle
        heuristic_func: Heuristic function to use (default: manhattan_distance)

    Returns:
        Solution path and statistics
    """
    # Step 1: Place the starting node into the OPEN list
    open_list = PriorityQueue()
    initial_state.h_value = heuristic_func(initial_state, goal_state)
    open_list.put((initial_state.h_value, id(initial_state), initial_state))

    # CLOSED list to store expanded nodes
    closed_list = set()

    # Statistics
    nodes_expanded = 0
    max_depth = 0

    print("Starting Greedy Best-First Search...")
    print("Initial State:")
    initial_state.display()
    print(f"Initial heuristic value: {initial_state.h_value}\n")

    while True:
        # Step 2: If the OPEN list is empty, Stop and return failure
        if open_list.empty():
            print("Failure: Goal state not reachable!")
            return None, nodes_expanded, max_depth

        # Step 3: Remove the node n with the lowest h(n) value from OPEN list
        _, _, current_state = open_list.get()

        # Add to CLOSED list
        closed_list.add(current_state)
        nodes_expanded += 1
        max_depth = max(max_depth, current_state.depth)

        print(f"Expanding node {nodes_expanded} (depth={current_state.depth}, h={current_state.h_value}):")
        current_state.display()

        # Step 4 & 5: Expand the node and check if any successor is goal
        successors = current_state.get_successors()

        for successor in successors:
            # Check if successor is goal node
            if successor.is_goal(goal_state):
                print("Goal state found!")
                return successor, nodes_expanded, max_depth

            # Step 6: Calculate heuristic and add to OPEN list if not visited
            if successor not in closed_list:
                # Check if already in open list (simplified - not checking open list)
                successor.h_value = heuristic_func(successor, goal_state)
                open_list.put((successor.h_value, id(successor), successor))

    # Step 7: Return to Step 2 (loop continues)

def get_solution_path(goal_state):
    """Reconstruct the solution path from goal to initial state"""
    path = []
    current = goal_state

    while current is not None:
        path.append(current)
        current = current.parent

    path.reverse()
    return path

def print_solution(solution_path):
    """Print the solution path"""
    print("\n" + "="*50)
    print("SOLUTION PATH")
    print("="*50)

    for i, state in enumerate(solution_path):
        if state.move:
            print(f"Step {i}: Move {state.move}")
        else:
            print(f"Step {i}: Initial State")
        state.display()

    print(f"Total moves: {len(solution_path) - 1}")

def main():
    """Main function to run the 8-puzzle solver"""

    # Example 1: Easy puzzle
    print("="*50)
    print("EXAMPLE 1: Easy Puzzle")
    print("="*50 + "\n")

    initial_board = [
        [1, 2, 3],
        [4, 0, 5],
        [7, 8, 6]
    ]

    goal_board = [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 0]
    ]

    initial_state = PuzzleState(initial_board)
    goal_state = PuzzleState(goal_board)

    # Solve using Manhattan distance heuristic
    solution, nodes_expanded, max_depth = greedy_best_first_search(
        initial_state, goal_state, manhattan_distance
    )

    if solution:
        path = get_solution_path(solution)
        print_solution(path)
        print(f"\nStatistics:")
        print(f"  Nodes expanded: {nodes_expanded}")
        print(f"  Maximum depth reached: {max_depth}")
        print(f"  Solution depth: {solution.depth}")

    print("\n" + "="*50)
    print("EXAMPLE 2: Medium Puzzle")
    print("="*50 + "\n")

    # Example 2: Medium difficulty
    initial_board2 = [
        [1, 2, 3],
        [0, 4, 6],
        [7, 5, 8]
    ]

    initial_state2 = PuzzleState(initial_board2)

    solution2, nodes_expanded2, max_depth2 = greedy_best_first_search(
        initial_state2, goal_state, manhattan_distance
    )

    if solution2:
        path2 = get_solution_path(solution2)
        print_solution(path2)
        print(f"\nStatistics:")
        print(f"  Nodes expanded: {nodes_expanded2}")
        print(f"  Maximum depth reached: {max_depth2}")
        print(f"  Solution depth: {solution2.depth}")

    # Demonstrate different heuristics
    print("\n" + "="*50)
    print("COMPARING HEURISTICS")
    print("="*50 + "\n")

    print("Using Misplaced Tiles Heuristic:")
    solution3, nodes_expanded3, max_depth3 = greedy_best_first_search(
        PuzzleState(initial_board), goal_state, misplaced_tiles
    )

    if solution3:
        print(f"\nMisplaced Tiles Results:")
        print(f"  Nodes expanded: {nodes_expanded3}")
        print(f"  Solution depth: {solution3.depth}")


if __name__ == "__main__":
    main()

"""
Interactive 8-Puzzle Solver using Greedy Best-First Search
Allows user to input custom initial states
"""



def get_board_input(prompt):
    """Get puzzle board input from user"""
    print(prompt)
    print("Enter 9 numbers (0-8) separated by spaces, where 0 is the blank tile")
    print("Example: 1 2 3 4 0 5 7 8 6")

    while True:
        try:
            user_input = input("\nEnter the puzzle: ").strip()
            numbers = [int(x) for x in user_input.split()]

            # Validate input
            if len(numbers) != 9:
                print("Error: You must enter exactly 9 numbers!")
                continue

            if set(numbers) != set(range(9)):
                print("Error: You must use each number from 0-8 exactly once!")
                continue

            # Convert to 3x3 board
            board = [
                numbers[0:3],
                numbers[3:6],
                numbers[6:9]
            ]

            return board

        except ValueError:
            print("Error: Please enter valid numbers!")
        except Exception as e:
            print(f"Error: {e}")


def choose_heuristic():
    """Let user choose heuristic function"""
    print("\n" + "="*50)
    print("Choose Heuristic Function:")
    print("="*50)
    print("1. Manhattan Distance (Recommended)")
    print("   - Sum of distances of each tile from goal position")
    print("   - More accurate and efficient")
    print()
    print("2. Misplaced Tiles")
    print("   - Count of tiles not in goal position")
    print("   - Simpler but less efficient")
    print()

    while True:
        choice = input("Enter your choice (1 or 2): ").strip()
        if choice == "1":
            return manhattan_distance, "Manhattan Distance"
        elif choice == "2":
            return misplaced_tiles, "Misplaced Tiles"
        else:
            print("Invalid choice! Please enter 1 or 2.")


def is_solvable(board):
    """
    Check if the 8-puzzle is solvable
    A puzzle is solvable if the number of inversions is even
    """
    # Flatten the board and remove blank (0)
    flat = []
    for row in board:
        for val in row:
            if val != 0:
                flat.append(val)

    # Count inversions
    inversions = 0
    for i in range(len(flat)):
        for j in range(i + 1, len(flat)):
            if flat[i] > flat[j]:
                inversions += 1

    return inversions % 2 == 0


def main():
    """Main interactive function"""
    print("="*60)
    print("        8-PUZZLE SOLVER - GREEDY BEST-FIRST SEARCH")
    print("="*60)
    print()
    print("This program solves the 8-puzzle using Greedy Best-First Search.")
    print("The blank tile is represented by 0 (displayed as *).")
    print()

    # Default goal state
    goal_board = [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 0]
    ]

    print("Default Goal State:")
    goal_state = PuzzleState(goal_board)
    goal_state.display()

    while True:
        # Get initial state from user
        print("\n" + "="*60)
        initial_board = get_board_input("Enter Initial State:")
        initial_state = PuzzleState(initial_board)

        print("\nYour initial state:")
        initial_state.display()

        # Check if puzzle is solvable
        if not is_solvable(initial_board):
            print("⚠️  WARNING: This puzzle is NOT SOLVABLE!")
            print("The configuration you entered cannot reach the goal state.")
            retry = input("\nDo you want to try a different puzzle? (y/n): ").strip().lower()
            if retry != 'y':
                break
            continue

        # Check if already at goal
        if initial_state.is_goal(goal_state):
            print("✓ The initial state is already the goal state!")
            retry = input("\nDo you want to solve another puzzle? (y/n): ").strip().lower()
            if retry != 'y':
                break
            continue

        # Choose heuristic
        heuristic_func, heuristic_name = choose_heuristic()

        # Solve the puzzle
        print("\n" + "="*60)
        print(f"Solving with {heuristic_name} heuristic...")
        print("="*60 + "\n")

        solution, nodes_expanded, max_depth = greedy_best_first_search(
            initial_state, goal_state, heuristic_func
        )

        if solution:
            # Display solution
            path = get_solution_path(solution)
            print_solution(path)

            print("\n" + "="*60)
            print("STATISTICS")
            print("="*60)
            print(f"Heuristic Used: {heuristic_name}")
            print(f"Nodes Expanded: {nodes_expanded}")
            print(f"Maximum Depth Reached: {max_depth}")
            print(f"Solution Depth (Number of Moves): {solution.depth}")
            print(f"Average Branching Factor: {nodes_expanded / max(solution.depth, 1):.2f}")
        else:
            print("\n❌ Failed to find solution!")

        # Ask if user wants to solve another puzzle
        print("\n" + "="*60)
        again = input("Do you want to solve another puzzle? (y/n): ").strip().lower()
        if again != 'y':
            break

    print("\n" + "="*60)
    print("Thank you for using the 8-Puzzle Solver!")
    print("="*60)


if __name__ == "__main__":
    main()

"""
Comparison: Greedy Best-First Search vs A* Search
Demonstrates the difference between informed search algorithms
"""




def a_star_search(initial_state, goal_state, heuristic_func=manhattan_distance):
    """
    A* Search Algorithm
    f(n) = g(n) + h(n)
    where g(n) is the cost from start to n
    and h(n) is the heuristic estimate from n to goal
    """
    open_list = PriorityQueue()

    # Calculate f(n) = g(n) + h(n)
    initial_state.h_value = heuristic_func(initial_state, goal_state)
    initial_state.g_value = 0  # Cost from start
    f_value = initial_state.g_value + initial_state.h_value

    open_list.put((f_value, id(initial_state), initial_state))

    closed_list = set()
    nodes_expanded = 0
    max_depth = 0

    print("Starting A* Search...")
    print("Initial State:")
    initial_state.display()
    print(f"Initial f(n) = g(n) + h(n) = {initial_state.g_value} + {initial_state.h_value} = {f_value}\n")

    while True:
        if open_list.empty():
            print("Failure: Goal state not reachable!")
            return None, nodes_expanded, max_depth

        _, _, current_state = open_list.get()

        if current_state in closed_list:
            continue

        closed_list.add(current_state)
        nodes_expanded += 1
        max_depth = max(max_depth, current_state.depth)

        f_val = current_state.g_value + current_state.h_value
        print(f"Expanding node {nodes_expanded} (depth={current_state.depth}, g={current_state.g_value}, h={current_state.h_value}, f={f_val}):")
        current_state.display()

        successors = current_state.get_successors()

        for successor in successors:
            if successor.is_goal(goal_state):
                print("Goal state found!")
                successor.g_value = current_state.g_value + 1
                successor.h_value = 0
                return successor, nodes_expanded, max_depth

            if successor not in closed_list:
                successor.g_value = current_state.g_value + 1  # Each move costs 1
                successor.h_value = heuristic_func(successor, goal_state)
                f_value = successor.g_value + successor.h_value
                open_list.put((f_value, id(successor), successor))


def greedy_search_verbose(initial_state, goal_state, heuristic_func=manhattan_distance):
    """Greedy search with verbose output for comparison"""
    open_list = PriorityQueue()
    initial_state.h_value = heuristic_func(initial_state, goal_state)
    open_list.put((initial_state.h_value, id(initial_state), initial_state))

    closed_list = set()
    nodes_expanded = 0
    max_depth = 0

    print("Starting Greedy Best-First Search...")
    print("Initial State:")
    initial_state.display()
    print(f"Initial h(n) = {initial_state.h_value}\n")

    while True:
        if open_list.empty():
            print("Failure: Goal state not reachable!")
            return None, nodes_expanded, max_depth

        _, _, current_state = open_list.get()
        closed_list.add(current_state)
        nodes_expanded += 1
        max_depth = max(max_depth, current_state.depth)

        print(f"Expanding node {nodes_expanded} (depth={current_state.depth}, h={current_state.h_value}):")
        current_state.display()

        successors = current_state.get_successors()

        for successor in successors:
            if successor.is_goal(goal_state):
                print("Goal state found!")
                return successor, nodes_expanded, max_depth

            if successor not in closed_list:
                successor.h_value = heuristic_func(successor, goal_state)
                open_list.put((successor.h_value, id(successor), successor))


def compare_algorithms(initial_board, goal_board):
    """Compare Greedy and A* search on the same puzzle"""

    print("="*70)
    print("COMPARING GREEDY BEST-FIRST SEARCH vs A* SEARCH")
    print("="*70)
    print()

    # Run Greedy search
    print("+"*70)
    print("GREEDY BEST-FIRST SEARCH (uses only h(n))")
    print("+"*70)
    print()

    initial_state_greedy = PuzzleState(initial_board)
    goal_state = PuzzleState(goal_board)

    solution_greedy, nodes_greedy, depth_greedy = greedy_search_verbose(
        initial_state_greedy, goal_state, manhattan_distance
    )

    # Run A* search
    print("\n" + "+"*70)
    print("A* SEARCH (uses g(n) + h(n))")
    print("+"*70)
    print()

    initial_state_astar = PuzzleState(initial_board)

    solution_astar, nodes_astar, depth_astar = a_star_search(
        initial_state_astar, goal_state, manhattan_distance
    )

    # Compare results
    print("\n" + "="*70)
    print("COMPARISON RESULTS")
    print("="*70)
    print()

    print(f"{'Metric':<30} {'Greedy':<20} {'A*':<20}")
    print("-"*70)

    if solution_greedy:
        path_greedy = get_solution_path(solution_greedy)
        print(f"{'Solution Found':<30} {'Yes':<20} {'Yes' if solution_astar else 'No':<20}")
        print(f"{'Solution Length (moves)':<30} {len(path_greedy)-1:<20} {len(get_solution_path(solution_astar))-1 if solution_astar else 'N/A':<20}")
        print(f"{'Nodes Expanded':<30} {nodes_greedy:<20} {nodes_astar:<20}")
        print(f"{'Maximum Depth Reached':<30} {depth_greedy:<20} {depth_astar:<20}")
        print()

        print("Key Differences:")
        print("-"*70)
        print("• Greedy uses only h(n) - estimates distance to goal")
        print("  → Faster but may not find optimal solution")
        print()
        print("• A* uses g(n) + h(n) - actual cost + estimated cost")
        print("  → Guarantees optimal solution (with admissible heuristic)")
        print()

        if len(path_greedy) > len(get_solution_path(solution_astar)):
            print(f"✓ A* found a shorter solution!")
            print(f"  A* solution: {len(get_solution_path(solution_astar))-1} moves")
            print(f"  Greedy solution: {len(path_greedy)-1} moves")
        elif len(path_greedy) == len(get_solution_path(solution_astar)):
            print("✓ Both algorithms found solutions of equal length")
        else:
            print("⚠ Greedy found a shorter path (unusual - depends on heuristic)")
        print()

        if nodes_greedy < nodes_astar:
            print(f"✓ Greedy expanded fewer nodes ({nodes_greedy} vs {nodes_astar})")
        else:
            print(f"✓ A* was more efficient in node expansion")


def main():
    """Run comparison examples"""

    # Example 1: Case where Greedy might not be optimal
    print("\n" + "="*70)
    print("EXAMPLE 1: Puzzle where algorithms may differ")
    print("="*70)
    print()

    initial_board1 = [
        [1, 2, 3],
        [4, 0, 5],
        [7, 8, 6]
    ]

    goal_board = [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 0]
    ]

    compare_algorithms(initial_board1, goal_board)

    # Example 2: More complex puzzle
    print("\n\n" + "="*70)
    print("EXAMPLE 2: More complex puzzle")
    print("="*70)
    print()

    initial_board2 = [
        [1, 2, 3],
        [0, 4, 6],
        [7, 5, 8]
    ]

    compare_algorithms(initial_board2, goal_board)

    print("\n" + "="*70)
    print("SUMMARY")
    print("="*70)
    print("""
When to use each algorithm:

Greedy Best-First Search:
  ✓ When you need a quick solution
  ✓ When optimality is not critical
  ✓ When the heuristic is very accurate
  ✓ Limited computational resources

A* Search:
  ✓ When you need the optimal solution
  ✓ When solution quality matters more than speed
  ✓ When you have a good admissible heuristic
  ✓ Sufficient computational resources available
""")


if __name__ == "__main__":
    main()

