# -*- coding: utf-8 -*-
"""Uninformed Search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-hgr5YfFfcRn80PJZdIZaKYr8mhglUi

## **8-Puzzle Problem Solver using Breadth First Search (BFS)**
"""

from collections import deque
from typing import List, Tuple, Optional, Set

class PuzzleState:
    """Represents a state of the 8-puzzle"""

    def __init__(self, board: List[List[int]], parent=None, move: str = ""):
        self.board = board
        self.parent = parent
        self.move = move
        self.blank_pos = self._find_blank()

    def _find_blank(self) -> Tuple[int, int]:
        """Find the position of the blank (0) tile"""
        for i in range(3):
            for j in range(3):
                if self.board[i][j] == 0:
                    return (i, j)
        return (0, 0)

    def get_board_tuple(self) -> Tuple:
        """Convert board to tuple for hashing"""
        return tuple(tuple(row) for row in self.board)

    def is_goal(self, goal_state) -> bool:
        """Check if current state matches goal state"""
        return self.board == goal_state

    def get_neighbors(self) -> List['PuzzleState']:
        """Generate all possible moves from current state"""
        neighbors = []
        row, col = self.blank_pos

        # Possible moves: Up, Down, Left, Right
        moves = [
            (-1, 0, "UP"),
            (1, 0, "DOWN"),
            (0, -1, "LEFT"),
            (0, 1, "RIGHT")
        ]

        for dr, dc, move_name in moves:
            new_row, new_col = row + dr, col + dc

            # Check if move is valid
            if 0 <= new_row < 3 and 0 <= new_col < 3:
                # Create new board
                new_board = [row[:] for row in self.board]
                # Swap blank with tile
                new_board[row][col], new_board[new_row][new_col] = \
                    new_board[new_row][new_col], new_board[row][col]

                neighbors.append(PuzzleState(new_board, self, move_name))

        return neighbors

    def print_board(self):
        """Print the board in a readable format"""
        for row in self.board:
            print(" ".join(str(x) if x != 0 else " " for x in row))
        print()

def bfs_solve(initial_state: List[List[int]], goal_state: List[List[int]]) -> Optional[PuzzleState]:
    """
    Solve 8-puzzle using Breadth First Search

    Args:
        initial_state: Starting configuration of the puzzle
        goal_state: Goal configuration of the puzzle

    Returns:
        Solution state if found, None otherwise
    """

    # Create initial state
    start = PuzzleState(initial_state)

    # Check if initial state is goal
    if start.is_goal(goal_state):
        return start

    # Initialize frontier (queue) and visited set
    frontier = deque([start])
    visited: Set[Tuple] = {start.get_board_tuple()}

    nodes_explored = 0

    # BFS loop
    while frontier:
        # Remove node from front of queue
        current_node = frontier.popleft()
        nodes_explored += 1

        # Generate and explore neighbors
        for neighbor in current_node.get_neighbors():
            neighbor_tuple = neighbor.get_board_tuple()

            # Skip if already visited
            if neighbor_tuple in visited:
                continue

            # Check if goal is reached
            if neighbor.is_goal(goal_state):
                print(f"Solution found! Nodes explored: {nodes_explored}")
                return neighbor

            # Add to frontier and visited
            visited.add(neighbor_tuple)
            frontier.append(neighbor)

    print(f"No solution found. Nodes explored: {nodes_explored}")
    return None

def get_solution_path(solution_state: PuzzleState) -> List[PuzzleState]:
    """Reconstruct path from initial state to solution"""
    path = []
    current = solution_state

    while current is not None:
        path.append(current)
        current = current.parent

    return list(reversed(path))

def print_solution(solution_state: Optional[PuzzleState]):
    """Print the solution path"""
    if solution_state is None:
        print("No solution exists!")
        return

    path = get_solution_path(solution_state)

    print(f"\n{'='*40}")
    print(f"Solution found in {len(path) - 1} moves!")
    print(f"{'='*40}\n")

    for i, state in enumerate(path):
        if i == 0:
            print("Initial State:")
        elif i == len(path) - 1:
            print(f"Step {i}: {state.move} -> GOAL STATE")
        else:
            print(f"Step {i}: {state.move}")

        state.print_board()

# Main execution
if __name__ == "__main__":
    # Define initial and goal states from the lab document
    initial_state = [
        [2, 8, 3],
        [1, 6, 4],
        [7, 0, 5]
    ]

    goal_state = [
        [1, 2, 3],
        [8, 0, 4],
        [7, 6, 5]
    ]

    print("8-PUZZLE SOLVER USING BREADTH FIRST SEARCH")
    print("="*40)
    print("\nInitial State:")
    PuzzleState(initial_state).print_board()

    print("Goal State:")
    PuzzleState(goal_state).print_board()

    print("Searching for solution using BFS...")
    print("-"*40)

    # Solve the puzzle
    solution = bfs_solve(initial_state, goal_state)

    # Print the solution
    print_solution(solution)

